"""End-to-end webhook lifecycle:

    create endpoint → test.ping → webhook.site receives POST
                   → verify signature with SDK → delete endpoint

This is the single most load-bearing end-to-end test the SDK can run:
it proves that the server's signing logic and the SDK's
``Webhook.verify`` agree on the exact same bytes. If this fails,
every SDK consumer's webhook handler is broken.
"""

from __future__ import annotations

import base64
import json

from legalize import Legalize, Webhook


def _decode_body(content: str | None, content_base64: bool) -> bytes:
    """webhook.site may return the body either as raw UTF-8 or base64.

    When ``request.content_base64`` is true, ``request.content`` is a
    base64 string. Otherwise it's the verbatim body. We always return
    raw bytes — which is what ``Webhook.verify`` needs, since the
    signature is computed over the exact bytes the server sent.
    """
    if content is None:
        return b""
    if content_base64:
        return base64.b64decode(content)
    return content.encode("utf-8")


def test_create_ping_verify_delete(client: Legalize, webhook_site, test_prefix: str):
    token = webhook_site.create_token()
    target_url = webhook_site.url_for(token)

    # Note: ``test.ping`` is generated by the server's /test endpoint, it
    # is not a subscribable event. Subscribe to a real one instead.
    endpoint = client.webhooks.create(
        url=target_url,
        event_types=["law.updated"],
        description=test_prefix,
    )
    endpoint_id = int(endpoint["id"])
    secret = endpoint["secret"]
    assert secret.startswith("whsec_")

    try:
        # Trigger a test.ping — the server signs + POSTs synchronously.
        result = client.webhooks.test(endpoint_id)
        assert result.get("status") == "success", result

        # The delivery should arrive at webhook.site within seconds.
        request = webhook_site.wait_for_request(token, timeout=30.0)

        headers = {k.lower(): v for k, v in (request.get("headers") or {}).items()}
        # webhook.site returns headers as {name: [value, ...]}
        sig_header = _first(headers.get("x-legalize-signature"))
        ts_header = _first(headers.get("x-legalize-timestamp"))
        event_header = _first(headers.get("x-legalize-event"))
        assert sig_header and sig_header.startswith("v1="), f"bad sig header: {sig_header}"
        assert ts_header and ts_header.isdigit(), f"bad ts header: {ts_header}"
        assert event_header == "test.ping"

        body_bytes = _decode_body(request.get("content"), bool(request.get("content_base64")))

        # The whole point: Webhook.verify succeeds against real server output.
        # Use a generous tolerance — webhook.site may take a few seconds
        # to show the request, and the test might run a bit later.
        event = Webhook.verify(
            payload=body_bytes,
            sig_header=sig_header,
            timestamp=ts_header,
            secret=secret,
            tolerance=900,  # 15 minutes — plenty for polling delay
        )
        assert event.type == "test.ping"
        assert event.id.startswith("evt_test_")

        # Sanity on the raw body shape
        parsed = json.loads(body_bytes)
        assert parsed.get("event_type") == "test.ping"
    finally:
        try:
            client.webhooks.delete(endpoint_id)
        except Exception:  # noqa: S110 — best-effort cleanup
            pass


def test_list_shows_our_endpoint(client: Legalize, webhook_site, test_prefix: str):
    token = webhook_site.create_token()
    target_url = webhook_site.url_for(token)

    endpoint = client.webhooks.create(
        url=target_url,
        event_types=["law.updated", "law.created"],
        countries=["es"],
        description=test_prefix,
    )
    endpoint_id = int(endpoint["id"])
    try:
        listed = client.webhooks.list()
        ours = [ep for ep in listed if int(ep["id"]) == endpoint_id]
        assert len(ours) == 1
        assert ours[0]["url"] == target_url
        assert set(ours[0]["event_types"]) == {"law.updated", "law.created"}
        # ``secret`` MUST NOT be returned on list — only on create.
        assert "secret" not in ours[0]
    finally:
        client.webhooks.delete(endpoint_id)


def test_update_then_delete(client: Legalize, webhook_site, test_prefix: str):
    token = webhook_site.create_token()
    endpoint = client.webhooks.create(
        url=webhook_site.url_for(token),
        event_types=["law.updated"],
        description=test_prefix,
    )
    endpoint_id = int(endpoint["id"])
    try:
        updated = client.webhooks.update(endpoint_id, enabled=False)
        assert updated.get("enabled") is False

        fetched = client.webhooks.retrieve(endpoint_id)
        assert fetched["enabled"] is False
    finally:
        client.webhooks.delete(endpoint_id)

    # Post-delete: a retrieve should 404.
    import pytest

    from legalize import NotFoundError

    with pytest.raises(NotFoundError):
        client.webhooks.retrieve(endpoint_id)


def _first(value):
    """Normalize webhook.site's header shape: returns the first value.

    webhook.site returns headers as either ``"X-H": "v"`` or
    ``"X-H": ["v"]`` depending on version. Handle both.
    """
    if value is None:
        return None
    if isinstance(value, list):
        return value[0] if value else None
    return value
