/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check for monitoring. No authentication required.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Countries
         * @description List all available countries with law counts.
         */
        get: operations["api_countries_api_v1_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Endpoints
         * @description List all webhook endpoints for the authenticated user.
         */
        get: operations["list_endpoints_api_v1_webhooks_get"];
        put?: never;
        /**
         * Create Endpoint
         * @description Create a webhook endpoint. Returns the signing secret ONCE.
         */
        post: operations["create_endpoint_api_v1_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{endpoint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Endpoint
         * @description Get details for a specific webhook endpoint.
         */
        get: operations["get_endpoint_api_v1_webhooks__endpoint_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Endpoint
         * @description Delete a webhook endpoint.
         */
        delete: operations["delete_endpoint_api_v1_webhooks__endpoint_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Endpoint
         * @description Update a webhook endpoint.
         */
        patch: operations["update_endpoint_api_v1_webhooks__endpoint_id__patch"];
        trace?: never;
    };
    "/api/v1/webhooks/{endpoint_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Deliveries
         * @description List delivery attempts for an endpoint. Filter by status: failed, success, pending.
         */
        get: operations["list_deliveries_api_v1_webhooks__endpoint_id__deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{endpoint_id}/deliveries/{delivery_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Failed Delivery
         * @description Retry a failed webhook delivery. Re-sends the original event payload.
         */
        post: operations["retry_failed_delivery_api_v1_webhooks__endpoint_id__deliveries__delivery_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{endpoint_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Test Event
         * @description Send a test.ping event to verify the endpoint is working.
         */
        post: operations["send_test_event_api_v1_webhooks__endpoint_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Jurisdictions
         * @description List jurisdictions (regions/states) within a country.
         */
        get: operations["api_jurisdictions_api_v1__country__jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/law-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Law Types
         * @description List law types available in a country (e.g. constitucion, ley, real_decreto).
         */
        get: operations["api_law_types_api_v1__country__law_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/laws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api List Laws
         * @description Search and list laws for a country.
         *
         *     Without `q`: returns a paginated list of all laws, sorted by date (newest first).
         *     With `q`: full-text search with relevance ranking.
         *
         *     All filters (law_type, year, status, jurisdiction, from_date, to_date) apply
         *     in both listing and search modes. Use `sort` to change order.
         */
        get: operations["api_list_laws_api_v1__country__laws_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/laws/{law_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Law
         * @description Get a complete law with full Markdown content.
         *
         *     Fetches content from GitHub. Slower than /meta for metadata-only use cases.
         *     Free tier: basic fields + content_md.
         *     Pro tier: adds department, source, last_updated, extra (country-specific metadata).
         */
        get: operations["api_get_law_api_v1__country__laws__law_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/laws/{law_id}/at/{sha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Law At Commit
         * @description Time-travel: get the full text of a law at a specific historical version.
         */
        get: operations["api_law_at_commit_api_v1__country__laws__law_id__at__sha__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/laws/{law_id}/commits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Commits
         * @description Get the git commit history of a law. Each commit represents a version change.
         */
        get: operations["api_get_commits_api_v1__country__laws__law_id__commits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/laws/{law_id}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Law Meta
         * @description Get law metadata only. Fast — no content fetching from GitHub.
         *
         *     Free tier: basic fields (id, title, status, dates, country, law_type).
         *     Pro tier: adds department, source, last_updated, extra (country-specific metadata).
         */
        get: operations["api_get_law_meta_api_v1__country__laws__law_id__meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/laws/{law_id}/reforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Get Reforms
         * @description Get the reform history of a law. Each reform is a legislative change.
         */
        get: operations["api_get_reforms_api_v1__country__laws__law_id__reforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{country}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Stats
         * @description Get aggregate statistics: reform activity by year, most reformed laws, and law types.
         */
        get: operations["api_stats_api_v1__country__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Commit */
        Commit: {
            /** Date */
            date: string;
            /** Message */
            message: string;
            /** Sha */
            sha: string;
        };
        /** CommitsResponse */
        CommitsResponse: {
            /** Commits */
            commits: components["schemas"]["Commit"][];
            /** Law Id */
            law_id: string;
        };
        /** CountryInfo */
        CountryInfo: {
            /** Count */
            count: number;
            /** Country */
            country: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JurisdictionInfo */
        JurisdictionInfo: {
            /** Count */
            count: number;
            /** Jurisdiction */
            jurisdiction?: string | null;
        };
        /** LawAtCommitResponse */
        LawAtCommitResponse: {
            /** Content Md */
            content_md: string;
            /** Law Id */
            law_id: string;
            /** Sha */
            sha: string;
        };
        /**
         * LawDetail
         * @description Full law with Markdown content (fetched from GitHub).
         */
        LawDetail: {
            /** Article Count */
            article_count?: number | null;
            /** Content Md */
            content_md?: string | null;
            /** Country */
            country: string;
            /** Department */
            department?: string | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
            /** Frontmatter */
            frontmatter?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /** Law Type */
            law_type: string;
            /** Publication Date */
            publication_date?: string | null;
            /** Short Title */
            short_title?: string | null;
            /** Source */
            source?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title: string;
        };
        /**
         * LawMeta
         * @description Law metadata without content. Lightweight — no GitHub fetch.
         */
        LawMeta: {
            /** Article Count */
            article_count?: number | null;
            /** Country */
            country: string;
            /** Department */
            department?: string | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Last Updated */
            last_updated?: string | null;
            /** Law Type */
            law_type: string;
            /** Publication Date */
            publication_date?: string | null;
            /** Short Title */
            short_title?: string | null;
            /** Source */
            source?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title: string;
        };
        /**
         * LawSearchResult
         * @description Law result with search snippet.
         */
        LawSearchResult: {
            /** Article Count */
            article_count?: number | null;
            /** Country */
            country: string;
            /** Id */
            id: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Law Type */
            law_type: string;
            /** Publication Date */
            publication_date?: string | null;
            /** Short Title */
            short_title?: string | null;
            /** Status */
            status?: string | null;
            /** Title */
            title: string;
            /** Title Snippet */
            title_snippet?: string | null;
        };
        /**
         * PaginatedLaws
         * @description Unified response for law listing and search.
         *
         *     When searching (query is not None), both ``total`` and ``count``
         *     are populated with the same value for backward compatibility.
         *     When listing, ``query`` and ``count`` are None.
         */
        PaginatedLaws: {
            /** Count */
            count?: number | null;
            /** Country */
            country: string;
            /** From Date */
            from_date?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Query */
            query?: string | null;
            /** Results */
            results: components["schemas"]["LawSearchResult"][];
            /** Sort */
            sort?: string | null;
            /** To Date */
            to_date?: string | null;
            /** Total */
            total: number;
        };
        /** Reform */
        Reform: {
            /** Articles Affected */
            articles_affected?: string | null;
            /** Date */
            date: string;
            /** Source Id */
            source_id?: string | null;
        };
        /** ReformsResponse */
        ReformsResponse: {
            /** Law Id */
            law_id: string;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Reforms */
            reforms: components["schemas"]["Reform"][];
            /** Total */
            total: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Country */
            country: string;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Law Types */
            law_types: string[];
            /** Most Reformed Laws */
            most_reformed_laws: {
                [key: string]: unknown;
            }[];
            /** Reform Activity By Year */
            reform_activity_by_year: {
                [key: string]: unknown;
            }[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebhookEndpointCreate */
        WebhookEndpointCreate: {
            /** Countries */
            countries?: string[] | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Event Types */
            event_types: string[];
            /** Url */
            url: string;
        };
        /** WebhookEndpointUpdate */
        WebhookEndpointUpdate: {
            /** Countries */
            countries?: string[] | null;
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Event Types */
            event_types?: string[] | null;
            /** Url */
            url?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_countries_api_v1_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryInfo"][];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_endpoints_api_v1_webhooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_endpoint_api_v1_webhooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEndpointCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_endpoint_api_v1_webhooks__endpoint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_endpoint_api_v1_webhooks__endpoint_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_endpoint_api_v1_webhooks__endpoint_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookEndpointUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_deliveries_api_v1_webhooks__endpoint_id__deliveries_get: {
        parameters: {
            query?: {
                page?: number;
                status?: string | null;
            };
            header?: never;
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry_failed_delivery_api_v1_webhooks__endpoint_id__deliveries__delivery_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint_id: number;
                delivery_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_test_event_api_v1_webhooks__endpoint_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_jurisdictions_api_v1__country__jurisdictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JurisdictionInfo"][];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_law_types_api_v1__country__law_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_list_laws_api_v1__country__laws_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                /** @description Filter by law type. Comma-separated for multiple: ley,constitucion */
                law_type?: string | null;
                /** @description Filter by publication year (4 digits) */
                year?: number | null;
                /** @description Filter by status: vigente, derogada */
                status?: string | null;
                /** @description Filter by jurisdiction code */
                jurisdiction?: string | null;
                /** @description Full-text search query */
                q?: string | null;
                /** @description Sort order: date_desc (default), date_asc, title */
                sort?: string | null;
                /** @description Filter from date (YYYY-MM-DD inclusive) */
                from_date?: string | null;
                /** @description Filter to date (YYYY-MM-DD inclusive) */
                to_date?: string | null;
            };
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLaws"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_get_law_api_v1__country__laws__law_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawDetail"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_law_at_commit_api_v1__country__laws__law_id__at__sha__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                law_id: string;
                sha: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawAtCommitResponse"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_get_commits_api_v1__country__laws__law_id__commits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitsResponse"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_get_law_meta_api_v1__country__laws__law_id__meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LawMeta"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_get_reforms_api_v1__country__laws__law_id__reforms_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                country: string;
                law_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReformsResponse"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_stats_api_v1__country__stats_get: {
        parameters: {
            query?: {
                jurisdiction?: string | null;
            };
            header?: never;
            path: {
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Missing, malformed, or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Monthly quota exceeded. Includes Retry-After header. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
